name: JorgeINCRivera
layout_spectrum: 1
typography_spectrum: 0.757803
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.007401
  lightness: 0.019736
  saturation: 0.01069
  rhythmicContrast: 0.008223
