color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.745797
  lightness: 0.851654
  rhythmicContrast: 0.886557
  saturation: 0.701507
layout_spectrum: 1
name: JorgeINCRivera
typography_spectrum: 0.757803
